// Generated by https://quicktype.io
import 'dart:convert';

String usuarioModelJson(UsuarioPost usuarioPost) =>
    json.encode(usuarioPost.toJson());

class UsuarioPost {
  int id;
  String nombre;
  String telefono;
  String contrasena;
  String correo;
  String token;

  UsuarioPost({
    this.id,
    this.nombre,
    this.telefono,
    this.contrasena,
    this.correo,
    this.token,
  });

  Map<String, dynamic> toJson() => {
        'nombre': nombre,
        'telefono': telefono,
        'contrasena': contrasena,
        'correo': correo,
        'token': token,
      };
}

class UsuarioGet {
  int id;
  String nombre;
  String telefono;
  String contrasena;
  String correo;
  String token;

  UsuarioGet({
    this.id,
    this.nombre,
    this.telefono,
    this.contrasena,
    this.correo,
    this.token,
  });

  UsuarioGet.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    nombre = json['nombre'];
    telefono = json['telefono'];
    contrasena = json['contrasena'];
    correo = json['correo'];
    token = json['token'];
  }
}
